bike_problem_config:
    station_count: 50
    bike_total_count: 1519
    truck_count: 2
    truck_capacity: 100
genetic_parameter:
    iteration_time: 300
    mutation_prob: 0.1
    crossover_prob: 0.9
    population_size: 100
    crossover_type: None
objective_parameter:
    phi: 5

#    3172 6495 10818

